---
title: "mental16_20"
author: "Leighton Li"
date: "2/25/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
stringsAsFactors = FALSE
library(tidyverse)
library(skimr)
```

```{r}
data = read_csv("~/Desktop/CAPSTONE/mental_health.csv")
data = data[,16:20]

# 16: Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?
# 17 Would you be willing to bring up a physical health issue with a potential employer in an interview?
# 18 Why or why not?
# 19 How willing would you be to share with friends and family that you have a mental illness?
# 20 Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?

factor = data[,-3]
text = data[,3] # question 18: why or why not. 
```


```{r}
#factor %>% sapply(levels)
unique(factor$prev_mh_anonimity)
unique(factor$future_ph_specification)
unique(factor$`mh_sharing_friends/fam_flag`)
unique(factor$mh_bad_response_workplace)
```
```{r}
factor %>% group_by(prev_mh_anonimity) %>% summarise(p=n()/2958) %>%
  ggplot(aes(prev_mh_anonimity,p))+
  geom_col() + geom_text(aes(label=p))
```

```{r}
factor %>% group_by(future_ph_specification) %>% summarise(p=n()/2958) %>%
  ggplot(aes(future_ph_specification,p))+
  geom_col() + geom_text(aes(label=p))
```

```{r}
factor %>% group_by(`mh_sharing_friends/fam_flag`) %>% summarise(p=n()/2958) %>%
  ggplot(aes(`mh_sharing_friends/fam_flag`,p))+
  geom_col() + geom_text(aes(label=p))
```

```{r}
factor %>% group_by(mh_bad_response_workplace) %>% summarise(p=n()/2958) %>%
  ggplot(aes(mh_bad_response_workplace,p))+
  geom_col() + geom_text(aes(label=p))
```

