---
title: "Green Bonds"
subtitle: BA888-Capstone Project
date: "1/31/2020"
output: html_document
---

**Team Members:** Alvaro Chinchayan, Leighton Li, Andrey Lifar, Yoki Liu, Yue Ping, Sherry Zuo

```{r}
library(readxl)
library(tidyverse)
library(dplyr)
library(tidyr)
library(gganimate)
library(ggplot2)
library(ggcorrplot)
library(ggExtra)
library(graphics)
library(ggalt)
library(gifski)
library(plotrix)
library(ggpmisc)
library(gapminder)
library(ggrepel)
library(png)
library(maps)
library(ggmap)
library(purrr)
library(cluster)
library(factoextra)
library(skimr)
library(corrplot)
library(lubridate)
```

```{r}
bloomberg <- read_excel("~/Desktop/bloomberg.xlsx")
```
```{r}
dim(bloomberg)
```
```{r}
names(bloomberg)
```
```{r}
colnames(bloomberg) = gsub(" ", "_", tolower(colnames(bloomberg)))
colnames(bloomberg) = gsub("&", "_", colnames(bloomberg))
```
```{r}
names(bloomberg)
```
```{r}
bloomberg$amount_issued<-as.numeric(bloomberg$amount_issued)
bloomberg$cpn<-as.numeric(bloomberg$cpn)
bloomberg$revenue<-as.numeric(bloomberg$revenue)
bloomberg$rev_growth<-as.numeric(bloomberg$rev_growth)
bloomberg$`energy_consumption_(mwh)`<-as.numeric(bloomberg$`energy_consumption_(mwh)`)
bloomberg$tot_assets<-as.numeric(bloomberg$tot_assets)
bloomberg$total_liab<-as.numeric(bloomberg$total_liab)
```
```{r}
skim(bloomberg)
```

```{r}
data=bloomberg%>%select(-Quarter_end, -ticker, -quarter_end, -Split_factor, -Shares_split_adjusted)
colmean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
bloomberg <- replace(bloomberg, TRUE, lapply(bloomberg, colmean))
```
```{r}
bloomberg %>%
  ggplot(aes(esg_disclosure_score)) +
  geom_bar(fill = "green")+
  theme(panel.background = element_rect(fill="white"))
```
```{r}
bloomberg %>%
  ggplot(aes(s_p_rating)) +
  geom_bar(fill = "green")+
  theme(panel.background = element_rect(fill="white"))
```
```{r}
View(bloomberg$s_p_rating)
```


```{r}
bloomberg %>% 
  transmute(count, SP_rating = ifelse(starts_with("A") ~ "A", starts_with("B") ~ "B"))%>%
  group_by(SP_rating)
```







#######
```{r}
ESG<-read_csv("~/Desktop/ESG indicator.csv")
Macro<-read_csv("~/Desktop/capstone_data.csv")
```
```{r}
names(ESG)
```

```{r}
names(Macro)
```
```{r}
colnames(ESG) = gsub(" ", "_", colnames(ESG))
colnames(ESG) = gsub("-", "_", colnames(ESG))
colnames(ESG) = gsub("/", "_", colnames(ESG))
colnames(ESG)<-tolower(colnames(ESG))
colnames(Macro) = gsub(" ", "_", colnames(Macro))
colnames(Macro) = gsub("-", "_", colnames(Macro))
colnames(Macro) = gsub("/", "_", colnames(Macro))
colnames(Macro)<-tolower(colnames(Macro))
```

```{r}
colnames(Macro)[2]<-"country_code"
```
```{r}
ESG2 <- select (ESG,-29)
```

```{r}
names(ESG2)
```
```{r}
Macro2 <- select (Macro,-10:-25)
names(Macro2)
```
```{r}
Macro2 <- select (Macro2,-34:-39)
names(Macro2)
```
```{r}
colnames(ESG2)[5:28]<-1996:2019
names(ESG2)
```

```{r}
Macro3 <- Macro2 %>% gather('year','value',10:33)
```
```{r}
ESG3 <- ESG2 %>% gather('year','value',5:28)
```
```{r}
unique(Macro$iso)
```
```{r}
unique(ESG3$country_code)
```
```{r}
ESG3 <- ESG3[-126308:-126312,]
```
```{r}
ESG3 <- ESG3 %>% drop_na(series_name)
```

```{r}
unique(ESG3$series_name)
```

```{r}
names(Macro3)
```
```{r}
Macro4<- select (Macro3,c(2,8,10,11))
```
```{r}
colnames(Macro4)[4]<-'GDP'
names(Macro4)
```
```{r}
ESG4 <- ESG3 %>% spread(series_name, value)
```
```{r}
final <- left_join(Macro4, ESG4, by = c("iso" = "country_code", "year" = "year"))
```
```{r}
colnames(final)[2]<-'Scale/GDP'
```


