---
title: "R Notebook"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(data.table)
```

```{r}
data<-read_csv("~/Desktop/mental_health.csv")
```
```{r}
data<-data[,2:29]
```
```{r}
names(data)
```
```{r}
#focus columns 10-14
data2<-data[, 10:14]
```
```{r}
head(data2)
```
```{r}
skimr::skim(data2)
```
#11
```{r}
##personal advice, delete the column mh_prod_impact_perc
#'If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?',
#mh_prod_impact_perc
x<-table(data2$mh_prod_impact_perc)
x
```
```{r}
str(x)
mh_impact_count<-as.vector(x)
mh_impact_percentage<-names(x)
mh_impact_count
mh_impact_percentage
```
```{r}
pct <- round(mh_impact_count/sum(mh_impact_count)*100)
mh_impact_percentage <- paste(mh_impact_percentage, pct) # add percents to labels
mh_impact_percentage <- paste(mh_impact_percentage,"%",sep="") # ad % to labels
pie(mh_impact_count,labels = mh_impact_percentage, col=rainbow(length(mh_impact_percentage)),
   main="Pie Chart of Mental Health Impact")
```
#12
```{r}
#'Do you have previous employers?'
#prev_employers_flag
#no missing value
y=table(data2$prev_employers_flag)
y
```
```{r}
str(y)
pre_employer_count<-as.vector(y)
pre_employer_percentage<-c("Have previous employers", "No previous employers")
pre_employer_count
pre_employer_percentage
```
```{r}
pct2 <- round(pre_employer_count/sum(pre_employer_count)*100)
pre_employer_percentage <- paste(pre_employer_percentage, pct2) # add percents to labels
pre_employer_percentage <- paste(pre_employer_percentage,"%",sep="") # ad % to labels
pie(pre_employer_count,labels = pre_employer_percentage, col=rainbow(length(pre_employer_percentage)),
   main="Pie Chart of Previous Employers Flag")
```
#13
```{r}
#'Have your previous employers provided mental health benefits?',
#prev_mh_benefits
z<-table(data2$prev_mh_benefits)
z
```
```{r}
str(z)
prev_mh_benefits_count<-as.vector(z)
prev_mh_benefits_percentage<-names(z)
prev_mh_benefits_count
prev_mh_benefits_percentage
```
```{r}
pct3 <- round(prev_mh_benefits_count/sum(prev_mh_benefits_count)*100)
prev_mh_benefits_percentage <- paste(prev_mh_benefits_percentage, pct3) # add percents to labels
prev_mh_benefits_percentage <- paste(prev_mh_benefits_percentage,"%",sep="") # ad % to labels
pie(prev_mh_benefits_count,labels = prev_mh_benefits_percentage, col=rainbow(length(prev_mh_benefits_percentage)),
   main="Pie Chart of Whether Previous Employers Provided Mental Health Benefits")
```
```{r}
data2$prev_mh_benefits=
  ifelse(is.na(data2$prev_mh_benefits)==T,999999,
         ifelse(data2$prev_mh_benefits=='No, none did',1,
                ifelse(data2$prev_mh_benefits=="I don't know",2,
                       ifelse(data2$prev_mh_benefits=='Some did',3,4))))
```
```{r}
table(data2$prev_mh_benefits)
```
#14
```{r}
#'Were you aware of the options for mental health care provided by your previous employers?',
#prev_mh_benefits_awareness
a<-table(data2$prev_mh_benefits_awareness)
a
```
```{r}
str(a)
prev_mh_benefits_awareness_count<-as.vector(a)
prev_mh_benefits_awareness_percentage<-names(a)
prev_mh_benefits_awareness_count
prev_mh_benefits_awareness_percentage
```
```{r}
pct4 <- round(prev_mh_benefits_awareness_count/sum(prev_mh_benefits_awareness_count)*100)
prev_mh_benefits_awareness_percentage <- paste(prev_mh_benefits_awareness_percentage, pct4) # add percents to labels
prev_mh_benefits_awareness_percentage <- paste(prev_mh_benefits_awareness_percentage,"%",sep="") # ad % to labels
pie(prev_mh_benefits_awareness_count,labels = prev_mh_benefits_awareness_percentage, col=rainbow(length(prev_mh_benefits_awareness_percentage)),
   main="Pie Chart of Whether Aware the MH Benefits by Previous Employers")
```

```{r}
data2$prev_mh_benefits_awareness=
  ifelse(is.na(data2$prev_mh_benefits_awareness)==T,999999,
         ifelse(data2$prev_mh_benefits_awareness=="N/A (none offered)",1,
                ifelse(data2$prev_mh_benefits_awareness=="N/A (was not aware)",2,
                       ifelse(data2$prev_mh_benefits_awareness=="N/A (not currently aware)",3,
                              ifelse(data2$prev_mh_benefits_awareness=="No, I only became aware later",4,
                                     ifelse(data2$prev_mh_benefits_awareness=="I was aware of some",5,6))))))
```
```{r}
table(data2$prev_mh_benefits_awareness)
```
#15
```{r}
#'Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?',
#prev_mh_discussion
b<-table(data2$prev_mh_discussion)
b
```
```{r}
str(b)
prev_mh_discussion_awareness_count<-as.vector(b)
prev_mh_discussion_awareness_percentage<-names(b)
prev_mh_discussion_awareness_count
prev_mh_discussion_awareness_percentage
```
```{r}
pct5 <- round(prev_mh_discussion_awareness_count/sum(prev_mh_discussion_awareness_count)*100)
prev_mh_discussion_awareness_percentage <- paste(prev_mh_discussion_awareness_percentage, pct5)
prev_mh_discussion_awareness_percentage <- paste(prev_mh_discussion_awareness_percentage,"%",sep="")
pie(prev_mh_discussion_awareness_count,labels = prev_mh_discussion_awareness_percentage, col=rainbow(length(prev_mh_discussion_awareness_percentage)),
   main="Pie Chart of Whether Discuss Mental Health with Previous Employers")
```
```{r}
data2$prev_mh_discussion=
  ifelse(is.na(data2$prev_mh_discussion)==T,999999,
         ifelse(data2$prev_mh_discussion=="None did",1,
                ifelse(data2$prev_mh_discussion=="I don't know",2,
                       ifelse(data2$prev_mh_discussion=="Some did",3,4))))
```
```{r}
table(data2$prev_mh_discussion)
```